carforyou/carforyou-api-client-pkg

src/types/models/index.ts

Extends listing analytics statistics by new `pdpViewsByFeature` statistic as described here:
https://autoricardo-ag.slack.com/archives/C0162APB0ET/p1593782639006900

feat: add pdpViewsByFeature to ListingAnalyticsStats

---

README.md
src/index.ts
src/services/search/autoAlarm.ts

Came across a wrong typed interface during my refactoring, fixed a couple of other things while on it. One commit per fix if you prefer to review commit by commit. (two for the swagger UI update as I missed some links)

fix: saved search return type

---

README.md
src/index.ts
src/services/car/__tests__/leasing.test.ts
src/services/car/leasing.ts
src/types/models/index.ts

Adds `sendLeasingInterest` api call. It will behave the same way message leas call behaves in terms of validation.
~~**note** the validation part is not yet implemented in the backend~~

feat: add leasing interest call

---

src/services/car/__tests__/leasing.test.ts
src/services/car/__tests__/messageLead.test.ts
src/services/car/leasing.ts

Turns out that `fetchLeasingFormUrl` expects reCaptcha header to be passed to return value. This was missed in the initial implementation

fix: add reCaptcha too the leasing call

---

bundlesize.config.json

The previous PR was a breaking change but didn't deploy, shall I merge this one as a breaking change or as a fix is ok?
And how can we block the PR in case the bundle size fails?

fix: increase bundle size

---

src/services/__tests__/dealer.test.ts
src/services/dealer.ts

Due to dealer promotion being created in multiple languages the `fetchDealer` call accepts an optional `language` option to get the right language version of promotion content.

feat: accept language parameter in dealer fetch

---

src/index.ts
src/types/models/dealerPromotion.ts

https://autoricardo.atlassian.net/browse/CAR-4933
removed `dealerCarouselPromotion` and using `dealerPromotionContent`
@carforyou/frontend should i release a major version or a minor should be sufficient?

feat: rename dealerCarouselPromotion to dealerPromotionContent

---

src/services/dealer.ts
src/services/product.ts

With https://github.com/carforyou/carforyou-api-client-pkg/pull/167 some of the GET requests where not only wrapped in the token refresh handler but also in the validation error function which breaks the intended behavior as they are just loading data an no validation takes place, so the consumer will never expect an enveloped 200 to be returned in case there is a 404 or something else goes wrong...

fix: there are no validation errors to handle on GET requests

---

src/lib/factories/listing.ts
src/types/models/listing.ts

Adds the new types to the Listing types.
refs: https://autoricardo-ag.slack.com/archives/C01A3ECLW7M/p1599821656058300

feat: add buyNow props to listing types

---

README.md

adds suggestion to use a local json mock server to mock specific api calls

chore: improve docs on mocking

---

src/index.ts
src/lib/factories/listing.ts
src/services/car/__tests__/inventory.test.ts
src/services/car/inventory.ts
src/types/models/listing.ts

Adds a call to transform an imported listing to a manual one which will be used in the edit imported listings feature.

feat: transform listing to manual

---

src/__tests__/base.test.ts
src/apiClient.ts
src/base.ts

ref https://autoricardo.atlassian.net/browse/CAR-5381
backend introduced a new version for the lead messages api. the api versioning applies per endpoint and we can't globally set the api version as we initially planned to. this adds capabilities to override the api version per-call

allow overriding the api version per-call

---

src/base.ts
src/services/car/__tests__/messageLead.test.ts
src/services/car/messageLead.ts
src/types/models/index.ts

ref https://autoricardo.atlassian.net/browse/CAR-5381
backend introduced a new version for the lead messages api where the lead message name is split into first/last name. changes types and does the api v2 request

Split first/last name in message lead

---

src/services/reporting/__tests__/carSales.test.ts
src/services/reporting/carSales.ts

I forgot to add the status as a parameter in the query when I extended the car-sales data.
https://reporting-service.preprod.carforyou.ch/swagger-ui/index.html#/Reporting/getDealerCarSalesUsingGET

fix: added status in the query

---

src/types/sort.ts

References
[CAR-6118](https://autoricardo.atlassian.net/browse/CAR-6118)
[CAR-6121](https://autoricardo.atlassian.net/browse/CAR-6121)
As a dealer, when visiting the overview page on DH, I want to be able to sort my listings by production year and external listing id

feat: add sorts EXTERNAL_LISTING_ID and PRODUCTION_YEAR

---

README.md
src/index.ts
src/lib/__tests__/convertParams.test.ts
src/lib/convertParams.ts
src/services/car/__tests__/messageLead.test.ts
src/services/car/messageLead.ts
src/services/search/__tests__/queryFormatting.test.ts
src/services/search/listingSearch.ts
src/types/params/leads.ts
src/types/params/listings.ts
src/types/sort.ts

References CAR-6537
Handled needed API endpoint filter needed for `createdDate` sorting and introduced types and logic required.

feat: types and logic for lead messages created-date sorting

---

README.md
src/index.ts
src/services/carSaleTracking/__tests__/dealerFeedback.test.ts
src/services/carSaleTracking/dealerFeedback.ts

References https://autoricardo.atlassian.net/browse/CAR-6693
API dealerFeedback -> https://car-sale-tracking-service.preprod.carforyou.ch/swagger-ui/index.html#/Dealer%20Feedback/createDealerFeedbackUsingPOST
Add new api to store data collected by the dealer feedback.

feat: add new api to store dealer feedback

---

src/lib/dateEncoding.ts

References https://autoricardo.atlassian.net/browse/CAR-5595
In listings, we get errors like the following and started cleaning `undefined` values with helpers. turns out this happens only for specific date fields, only on specific api endpoints:
```
SerializableError: Error serializing `.listing.firstRegistrationDate` returned from `getServerSideProps` in "/[languag
```
The solution is to return an explicit `null` and nextjs over in the projects is happy

fix: never return undefined for date fields

---

README.md
src/index.ts
src/services/car/__tests__/messageLead.test.ts
src/services/car/messageLead.ts

References https://autoricardo.atlassian.net/browse/CAR-6644
Added the delete api function for deleting/hiding dealer message leads 
`dealers/${dealerId}/message-leads/${messageLeadId}/hide`

feat: hide dealer message leads

---

README.md
src/index.ts
src/services/car/__tests__/messageLead.test.ts
src/services/car/messageLead.ts

References CAR-5985
Resend message leads. `dealers/${dealerId}/message-leads/${messageLeadId}/resend`
I'll add the swagger docs to the README once they're available

feat: resend message lead

---

README.md
src/index.ts
src/services/__tests__/dealer.test.ts
src/services/car/__tests__/inventory.test.ts
src/services/car/inventory.ts
src/services/dealer.ts

References [CAR-5997](https://autoricardo.atlassian.net/browse/CAR-5997) and [CAR-5998](https://autoricardo.atlassian.net/browse/CAR-59988)
To fulfil the requirements for WLS we allow the optional `association` params in `fetchDealerSuggestions` and introduce new methods `fetchDealerOrAssociationModels` and `fetchDealerOrAssociationMakes`.

feat: allow association for inventory and suggestion

---

README.md
src/index.ts
src/services/car/__tests__/inventory.test.ts
src/services/car/inventory.ts

BREAKING CHANGE: method removed
Removes API that was created for the WLS needs, but then switched to a different one when we introduced dealer associations support.

feat: remove deprecated fetchDealerModels call

---

src/index.ts
src/types/models/buyerFeedbackBatch.ts

https://api.preprod.carforyou.ch/car-sale/buyer-feedback-batch/key/1
It was missing the `buyerFeedbackEntries` type.

fix: adjust buyerFeedbackEntries type

---

src/services/search/__tests__/listingSearch.test.ts
src/services/search/listingSearch.ts

References [CAR-7301](https://autoricardo.atlassian.net/browse/CAR-7301)
When getting listings count we were not merging `cityId` and `radius` into a location object, which resulted in count not being updated when applying the radius filter

fix: ensure location filter is converted when getting count

---

src/lib/factories/listing.ts
src/types/models/listing.ts

BE is adding the vehicleUniverse on their side but we will change it and we will send it when we create a new listing

feat: add vehicleUniverse to the listing

---

README.md
src/index.ts
src/services/carSaleTracking/__tests__/subscription.test.ts
src/services/carSaleTracking/subscription.ts
src/types/models/carSales.ts

References https://www.figma.com/file/p8RIdxT0mcEQRf1g2dzpHa/2021---Q1---Reporting-%26-Billing?node-id=1207%3A295
This API should cover widget 3 and also provide info for total number of sales for widget 2:
https://dealer-service.preprod.carforyou.ch/swagger-ui/index.html#/Product/getValidCarSaleTrackingSubscriptionUsingGET
Extend api-client for the widgets

feat: added carSalesTrackingSubscription data

---

README.md
src/index.ts
src/services/reporting/__tests__/carSales.test.ts
src/services/reporting/carSales.ts
src/types/models/carSales.ts

References https://www.figma.com/file/p8RIdxT0mcEQRf1g2dzpHa/2021---Q1---Reporting-%26-Billing?node-id=1207%3A295
Sales vs Capping + current transactions - https://car-sale-tracking-service.preprod.carforyou.ch/swagger-ui/index.html#/Car%20Sale/countCarSalesUsingGET.
Extend api-client for the widgets

feat: added carSalesCount data

---

src/services/__tests__/product.test.ts
src/services/car/__tests__/inventory.test.ts
src/services/car/inventory.ts
src/services/product.ts

References CAR-7468 (https://autoricardo.atlassian.net/browse/CAR-7468)
Switch to the new bulk endpoints:
/dealers/{dealerId}/listings/archive --> /dealers/{dealerId}/listings/bulk-archive ✅
/listings/set-buy-now-eligibility --> /listings/bulk-set-buy-now-eligibility (skipped)
/dealers/{dealerId}/listings/transfer-to-manual --> /dealers/{dealerId}/listings/bulk-transfer-to-manual ✅
/dealers/{dealerId}/listings/products/purchase-and-use --> /dealers/{dealerId}/listings/products/bulk-purchase-and-use ✅
/dealers/{dealerId}/listings/car-sale/dealer-feedback --> /dealers/{dealerId}/listings/car-sale/bulk-dealer-feedback (skipped)
Note: The `skipped` ones have been skipped because there is no bulk action implemented for those so far.

feat(bulk_endpoints): switch to new bulk endpoints

---

src/types/params/listings.ts

References CAR-7482
Backend introduced a new filter 'searchAttributes' to replace deprecated 'options'

replace options with searchAttributes

---

.circleci/config.yml
src/services/__tests__/vehicle.test.ts
src/services/vehicle.ts

References [CAR-7875](https://autoricardo.atlassian.net/browse/CAR-7875)
https://autoricardo-ag.slack.com/archives/C8RRP2UQ4/p1624284136079200
When I search for VIN = WB1043001AZW29580 on Dealer Hub the list of results has 4132 pages because it returns an empty list of type ids which we use to fetch the types
https://github.com/carforyou/carforyou-dealerhub-web/pull/1389

fix: fetchFrameNumberTypes return empty array if no result

---

src/lib/factories/leads.ts
src/types/models/index.ts

References [CAR-7351](https://autoricardo.atlassian.net/browse/CAR-7351)
PR: https://github.com/carforyou/carforyou-dealerhub-web/pull/1402
As a dealer, I want to be able to easily identify the car that a potential customer is interested in in the leads center in dealer hub with my individual stock no. (= “Wagennummer”) so that I can work more efficiently and thus have more time to reply properly to my leads messages.

feat: add referenceId to MessageLeadListing

---

src/types/params/listings.ts

References https://autoricardo.atlassian.net/browse/CAR-8084
Listing PR -> https://github.com/carforyou/carforyou-listings-web/pull/3414
To be able to pass the hasBuyerProtectionOnly filter in the query, I need to add it in the `ListingFilterParams`.

feat: added hasBuyerProtectionOnly as filter param

---

README.md
src/index.ts
src/services/search/__tests__/listingSearch.test.ts
src/services/search/listingSearch.ts

References [CAR-8474](https://autoricardo.atlassian.net/browse/CAR-8474)
We remove needs assessment completely from the app. Therefore, the fetch method is no longer needed.

BREAKING CHANGE: remove needs assessment

---

src/services/search/__tests__/listingSearch.test.ts
src/services/search/listingSearch.ts

References https://autoricardo.atlassian.net/browse/CAR-8584
some listings on the search service can have `null` values for `gdbdScore`, but our code expects a valid value from an enum

fix: add a fallback value for gbdScore

---

README.md
src/services/car/__tests__/loan.test.ts
src/types/models/loan.ts

References [CAR-9530](https://autoricardo.atlassian.net/browse/CAR-9530)
They need the city when they do a credit score request. here are a number of multizip-usages (meaning different towns use the same zip)
Some of them even across canton borders. In order to do credit checks, both specific
town + canton are relevant.
Therefore, a dedicated choice for city by the user is mandatory

BREAKING CHANGE: Replace address with city for loan interest

---

src/types/models/index.ts

References [CAR-9548](https://autoricardo.atlassian.net/browse/CAR-9548)
Credaris requested to have a different order for employment types. Since we iterate over the object, we need to change it in api-client

fix: employment type order in loan interest

---

src/index.ts
src/lib/factories/listing.ts
src/types/models/listing.ts

References [CAR-9650](https://autoricardo.atlassian.net/browse/CAR-9650), [CAR-9271](https://autoricardo.atlassian.net/browse/CAR-9271)
backend would like to remove the field on their side. See here: https://autoricardo-ag.slack.com/archives/C8RRP2UQ4/p1643365928002200 and also here: https://github.com/carforyou/carforyou-integration-events-java/pull/139
https://github.com/carforyou/carforyou-dealerhub-web/pull/1875
https://github.com/carforyou/carforyou-listings-web/pull/4132

BREAKING CHANGE: remove image id for public apis

---

README.md
src/index.ts
src/services/__tests__/dealer.test.ts
src/services/car/__tests__/inventory.test.ts
src/services/car/inventory.ts
src/services/dealer.ts
src/services/option/__tests__/listing.test.ts
src/services/option/listing.ts
src/types/models/index.ts

References [CAR-9729](https://autoricardo.atlassian.net/browse/CAR-9729)
To fetch the data for the comparison tool, bulk fetch methods have been introduced. To see how they are used, here is the related PR in listings: https://github.com/carforyou/carforyou-listings-web/pull/4137

feat: add new methods to bulk fetch data for comparison tool

---

src/lib/factories/listing.ts
src/types/models/listing.ts

References [CAR-9733](https://autoricardo.atlassian.net/browse/CAR-9733)
Options that we want to show in the comparison tool are the ones that are used in the options filter (so that there is some unification and ability to compare). They are exposed as `searchAttributes` on the listing object.
**_note_** This PR is a perfect example of how API types from swagger would save us work

feat: expose searchAttributes
