- src/types/params/listings.ts
- [CAR-4484 - Filter Boosted Listing](https://autoricardo.atlassian.net/browse/CAR-4484)
> feat: add features

- src/types/models/index.ts
Adds some missing props to the Dealer interface
> fix: add dealerSourceGroup and dealerType to the dealer interface

- README.md
- src/index.ts
- src/services/car/__tests__/leasing.test.ts
- src/services/car/leasing.ts
Adds a call to fetch the leasing form URL from the backend
> feat: add leasing url api call

- src/index.ts
- src/lib/factories/listing.ts
- src/services/__tests__/dealer.test.ts
- src/services/dealer.ts
- src/types/models/dealerProfile.ts
- src/types/models/index.ts
- src/types/models/listing.ts
refs: https://autoricardo.atlassian.net/browse/CAR-4741
> BREAKING CHANGE: remove dealerSource

- README.md
- src/index.ts
- src/services/__tests__/dealer.test.ts
- src/services/dealer.ts
- src/services/product.ts
- src/types/models/dealerPromotion.ts
- src/types/models/index.ts
BREAKING CHANGE
- [CAR-4653 - Garage Carousel: Edit Page - Slogan, Date and Photo Upload](https://autoricardo.atlassian.net/browse/CAR-4653)
> feat: add dealer promotion apis

- package.json
- src/index.ts
- src/types/models/dealerPromotion.ts
- src/types/models/index.ts
- src/types/models/product.ts
Adds and updates some types for the dealer promotion feature
> feat: add type definitions for the dealer promotion feature

- src/services/search/__tests__/dealerSearch.test.ts
- src/services/search/dealerSearch.ts
- src/types/params/dealer.ts
- src/types/sort.ts
> feat: add previewId, change sort type in array

- src/services/dealer.ts
- src/services/product.ts
- [CAR-5007](https://autoricardo.atlassian.net/browse/CAR-5007)
> fix: wrap apis in withTokenRefresh

- src/index.ts
- src/lib/factories/__tests__/dealerSavedSearch.test.ts
- src/lib/factories/dealerSavedSearch.ts
- src/lib/toQueryString.ts
- src/services/search/autoAlarm.ts
- src/types/models/autoAlarm.ts
BREAKING CHANGE
Backend requested to remove the type: "auto-alarm"
DH update API: https://github.com/carforyou/carforyou-dealerhub-web/pull/718
> feat: remove type from auto-alarm

- .eslintrc.js
- package-lock.json
- package.json
- src/services/car/__tests__/inventoryData.test.ts
We closed renovate PR so a manual update is needed.
> chore: update eslint config

- src/types/params/listings.ts
> feat: add buy now filter

- README.md
- src/index.ts
- src/services/analytics.ts
- src/types/models/index.ts
- src/types/params/listings.ts
[CAR-5242 - Cockpit: listings and lead number](https://autoricardo.atlassian.net/browse/CAR-5242)
> feat: add listings and leads analytics api

- src/types/params/listings.ts
https://autoricardo.atlassian.net/browse/CAR-5391
extended the types to support querying for listing options, see https://autoricardo-ag.slack.com/archives/GBN03UZ3K/p1602594132293600
> feat: support searching for listing options

- README.md
- src/index.ts
- src/services/__tests__/dealer.test.ts
- src/services/dealer.ts
- src/types/models/dealerProfile.ts
- [CAR-5392](https://autoricardo.atlassian.net/browse/CAR-5392)
> feat: add matelso phone to dealer profile

- README.md
- src/index.ts
- src/services/__tests__/dealer.test.ts
- src/services/dealer.ts
- src/types/models/dealerProfile.ts
- [CAR-5290 - Cockpit: Whatsapp CTA phone no. entry with confirmation + BO notification](https://autoricardo.atlassian.net/browse/CAR-5290)
> feat: add requestWhatsappIntegration api and whatsapp number to dealer profile

- README.md
- src/index.ts
- src/services/__tests__/dealer.test.ts
- src/services/dealer.ts
- src/types/models/index.ts
- [CAR-5551 - EDIT DP: Add logo in dealer hub and show on DP](https://autoricardo.atlassian.net/browse/CAR-5551)
> feat: add setLogo api

- src/types/models/index.ts
> fix: make logo optional

- src/__tests__/base.test.ts
- src/base.ts
- src/services/car/__tests__/buyNowApplication.test.ts
- src/services/car/__tests__/leasing.test.ts
- src/services/car/__tests__/messageLead.test.ts
- src/services/car/__tests__/moneybackApplication.test.ts
https://autoricardo.atlassian.net/browse/CAR-5683
BREAKING CHANGE: `recaptchaToken` should no longer be passed with any request
> feat: remove recaptcha

- README.md
- src/index.ts
- src/lib/__tests__/path.test.ts
- src/lib/path.ts
- src/services/car/buyNowApplication.ts
- src/services/car/leasing.ts
- src/services/car/messageLead.ts
- src/services/car/moneybackApplication.ts
- src/services/reporting/__tests__/whatsapp.test.ts
- src/services/reporting/whatsapp.ts
- src/types/models/index.ts
References: [CAR-6006](https://autoricardo.atlassian.net/browse/CAR-6006)
New api to store data collected by the whatsapp modal
> feat: add postWhatsappTrackingEntry api

- src/base.ts
- src/services/__tests__/product.test.ts
- src/services/car/__tests__/image.test.ts
- src/services/car/__tests__/inventory.test.ts
- src/services/option/__tests__/listing.test.ts
- src/services/search/__tests__/autoAlarm.test.ts
- src/types/withValidationError.ts
Reference https://autoricardo-ag.slack.com/archives/C8RRP2UQ4/p1612885405003400
> feat: add globalErrors

- src/types/models/index.ts
feat: just add print-center to Dealer Entitlements
> feat: add print-center to Dealer Entitlements

- src/lib/factories/listing.ts
- src/types/models/listing.ts
I added otherServices fields.
Related ticket [6145](https://autoricardo.atlassian.net/browse/CAR-6145?atlOrigin=eyJpIjoiMjYyM2E3ZDRjZjUzNDNmMzhhMWIwYWRkZTI3MDQ0NmYiLCJwIjoiaiJ9)
> feat: add free text otherServices

- README.md
- src/index.ts
- src/services/reporting/__tests__/carSales.test.ts
- src/services/reporting/carSales.ts
- src/types/models/carSales.ts
References: 
> Jira https://autoricardo.atlassian.net/browse/CAR-6319
> API contract for fetching draft car sales https://reporting-service.preprod.carforyou.ch/swagger-ui/index.html#/Reporting/getDealerCarSalesUsingGET
Extend the carSales api-client
> feat: add carSales data builder

- README.md
- src/base.ts
- src/index.ts
- src/services/reporting/__tests__/callTracking.test.ts
- src/services/reporting/__tests__/whatsapp.test.ts
- src/services/reporting/callTracking.ts
- src/services/reporting/index.ts
- src/services/reporting/whatsapp.ts
- src/types/models/index.ts
- src/types/models/tracking.ts
Add the call tracking endpoint to the api client.
> feat: add callTracking endpoint

- README.md
- src/index.ts
- src/services/__tests__/dealer.test.ts
- src/services/dealer.ts
https://github.com/carforyou/carforyou-api-client-pkg/pull/224 we are using now support-cases
DH: https://github.com/carforyou/carforyou-dealerhub-web/pull/1010
> BREAKING CHANGE: removed requestWhatsAppIntegration and requestMatelsoIntegration

- README.md
- src/index.ts
- src/services/reporting/__tests__/carSales.test.ts
- src/services/reporting/carSales.ts
- src/types/models/carSales.ts
refs: https://autoricardo.atlassian.net/browse/CAR-6320
Adds PUT and DELETE actions for carSales rejections so the Dealer can reject draft carSales in the Client.
> feat(carSales): create and delete rejections

- .github/codeowners
- .github/pull_request_template.md
Keep the projects in sync and apply the same codeowners and PR template as for the listings project
> chore: add codeowners and pr template file

- README.md
- src/index.ts
- src/services/__tests__/vehicle.test.ts
- src/services/vehicle.ts
- src/types/models/index.ts
- src/types/params/types.ts
Ref: [CAR-6038](https://autoricardo.atlassian.net/browse/CAR-6038)
> feat: add vin

- src/types/models/listing.ts
References https://autoricardo.atlassian.net/browse/CAR-6622
Exposes description field for searchListing
> feat: adds description filed to baseListing

- README.md
- src/index.ts
- src/services/car/__tests__/inventoryData.test.ts
- src/services/car/inventoryData.ts
References CAR-6025
Adds fetch methods for:
- `inventory/first-publishing-date-age-groups`
- `inventory/last-price-modified-date-age-groups`
> Adds new methods for inventory types

- README.md
- package-lock.json
- src/index.ts
- src/services/car/__tests__/inventory.test.ts
- src/services/car/inventory.ts
References [CAR-6016](https://autoricardo.atlassian.net/browse/CAR-6016)
> feat: add new API getAllDealerFrameNumbers

- src/lib/factories/leads.ts
- src/types/models/index.ts
References https://autoricardo.atlassian.net/browse/CAR-6323
Add additional mock data and types for testDrive and videoCallPreference for leads overview page
> feat: add mock data and types for leads overview page

- src/index.ts
forgot to export them here feat: adds dealer-default-listing apis
> fix: export methods

- README.md
- src/index.ts
- src/services/car/__tests__/buyNow.test.ts
- src/services/car/buyNow.ts
- src/types/models/index.ts
References https://autoricardo.atlassian.net/browse/CAR-6546
Add and export a function to fetch the buy now configuration
> feat: Add fetchBuyNowConfiguration

- src/services/car/__tests__/defaultListing.test.ts
- src/services/car/defaultListing.ts
in a previous release i nested wring the params
> fix: api call for global Data

- src/services/__tests__/dealer.test.ts
- src/types/models/dealerProfile.ts
> feat: add website to dealer profile

- README.md
- src/index.ts
- src/services/car/__tests__/inventory.test.ts
- src/services/car/inventory.ts
Implementation of the [getAllDealerModelsUsingGET](https://carforyou-service.preprod.carforyou.ch/swagger-ui/index.html#/Inventory/getAllDealerModelsUsingGET
) API endpoint
> Add dealer fetch model Api

- README.md
- src/index.ts
- src/services/car/__tests__/inventory.test.ts
- src/services/car/inventory.ts
References CAR-6433
Adds a new method to bulk archive dealer listings
> feat: bulk archive for dealer listings

- src/lib/factories/leads.ts
- src/types/models/index.ts
References CAR-6653
add types and test data for price and mileage on leads overview page
> feat: add price and mileage types and test data

- src/index.ts
- src/lib/factories/listing.ts
- src/types/models/listing.ts
Expose new fields for globalData
> feat: adds fields to use for global data on listing level

- README.md
- package-lock.json
- src/index.ts
- src/services/__tests__/product.test.ts
- src/services/product.ts
> feat: adds new method for bulk purchasing

- README.md
- src/index.ts
- src/services/car/__tests__/defaultListing.test.ts
- src/services/car/defaultListing.ts
- src/types/models/dealerDefaultListing.ts
References [CAR-6131](https://autoricardo.atlassian.net/browse/CAR-6131?atlOrigin=eyJpIjoiMTk2OGE0MmIzZWM1NDRmNzgxMTA0MTA1NWJjNGMwOWQiLCJwIjoiaiJ9)
https://carforyou-service.preprod.carforyou.ch/swagger-ui/index.html#/Dealer%20Default%20Listing
Add endpoint for general external note
> feat: add general-external-note api

- src/lib/dateEncoding.ts
> fix: return null

- src/services/carSaleTracking/__tests__/dealerFeedback.test.ts
- src/services/carSaleTracking/dealerFeedback.ts
References https://autoricardo.atlassian.net/browse/CAR-6693
We need to add the accessToken for the authorized request.
> fix: added authorized request

- README.md
- src/index.ts
- src/services/car/__tests__/messageLead.test.ts
- src/services/car/messageLead.ts
References CAR-6636
Add Call Leads hide(delete) API endpoint
> feat: add call lead hide API endpoint

- src/services/dealer.ts
> fix: add missing pagination query

- README.md
- src/index.ts
- src/services/reporting/__tests__/buyerFeedbackBatch.test.ts
- src/services/reporting/buyerFeedbackBatch.ts
- src/types/models/buyerFeedbackBatch.ts
References https://autoricardo.atlassian.net/browse/CAR-6765
API ->  https://reporting-service.preprod.carforyou.ch/swagger-ui/index.html#/Reporting/getBuyerFeedbackBatchUsingGET
Extend the buyer feedback batch api-client
> feat: add buyerFeedbackBatch data builder

- package-lock.json
- src/types/models/carSales.ts
References [CAR-6695](https://autoricardo.atlassian.net/browse/CAR-6695?atlOrigin=eyJpIjoiY2Y3NjZmZmUwN2QwNDA5MzlkMDQ2NmVhMmRhOTM2ZjEiLCJwIjoiaiJ9)
Add 2 new fields : `hasDealerFeedback` and `dealerFeedbackReceivedDate`
> feat: add dealerfeedback fields to carSales

- README.md
- src/index.ts
- src/services/car/__tests__/inventory.test.ts
- src/services/car/inventory.ts
BREAKING CHANGE: remove mandatory fields API
We will have the list on DH and we wont fetch them from BE
> feat: remove mandatory fields API

- src/types/models/listing.ts
> fix: value of vehicleUniverse can only be car

- README.md
- package-lock.json
- src/index.ts
- src/services/carSaleTracking/__tests__/bulkDealerFeedback.test.ts
- src/services/carSaleTracking/bulkDealerFeedback.ts
References [CAR-7202](https://autoricardo.atlassian.net/browse/CAR-7202?atlOrigin=eyJpIjoiOTU4ZmUyNDAxOWQ2NGM4YWJlMDU5NjU0NWU3YjI0YmIiLCJwIjoiaiJ9)
https://car-sale-tracking-service.preprod.carforyou.ch/swagger-ui/index.html#/Dealer%20Feedback/bulkCreateDealerFeedbackUsingPOST
Add new api to store bulk data collected by the dealer feedback.
Thank you 😃
> feat: add bulkDealerFeedback

- README.md
- src/index.ts
- src/services/car/__tests__/inventoryData.test.ts
- src/services/car/inventoryData.ts
- src/services/referenceData.ts
References CAR-7494 (https://autoricardo.atlassian.net/browse/CAR-7494)
Switch to new endpoint that returns all enumerations instead of using API per enumeration (i.e. /bodytypes)
> feat(reference_data): add new method to fetch reference data

- .circleci/config.yml
- __tests__/setup/fetchMock.ts
- package-lock.json
- package.json
- renovate.json
following our convention of using the lts release
> chore: update node to v14

- src/services/reporting/carSales.ts
Related to [this PR](https://github.com/carforyou/carforyou-dealerhub-web/pull/1357)
> feat: fix carSalesRejection

- src/services/reporting/__tests__/carSales.test.ts
- src/types/models/carSales.ts
References https://autoricardo.atlassian.net/browse/CAR-7350
DH PR: https://github.com/carforyou/carforyou-dealerhub-web/pull/1421
> feat: extend CarSalesListing with referenceId

- src/lib/factories/listing.ts
- src/types/models/listing.ts
References https://github.com/carforyou/carforyou-dealerhub-web/pull/1468
Add the referenceId for the bulk feedback as well.
> feat: added referenceId into searchListing

- README.md
- package-lock.json
- src/index.ts
- src/services/__tests__/userNotification.test.ts
- src/services/userNotification.ts
- src/types/models/index.ts
References [CAR-8479](https://autoricardo.atlassian.net/browse/CAR-8479?atlOrigin=eyJpIjoiNjQyMDdhMTkxNTAxNGExY2IzMWFiY2M4NWFkZmM5NTIiLCJwIjoiaiJ9)
Add extendSavedSearch
> feat: add extendSavedSearch

- src/index.ts
> feat: export ListingSourceGroup type

- src/services/reporting/messageLeads.ts
References CAR-9204
Discussed with BE to add an additional optional param
> fix: add createdDateFrom

- README.md
- package-lock.json
- src/index.ts
- src/services/search/currentMakeModels.ts
- src/services/search/fullTextSearch.ts
References [CAR-8727](https://autoricardo.atlassian.net/browse/CAR-8727)
Backend implemented a more efficient way to recommend make/model types and deprecated the old API.
> BREAKING CHANGE: Replace make suggestions method

- README.md
- src/index.ts
- src/services/search/__tests__/listingSearch.test.ts
- src/services/search/listingSearch.ts
- src/types/params/listings.ts
References CAR-XXXX
New API to fetch aggregations
> feat: add aggregations api
